import path from "node:path";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { Express } from "express";
import { connectPageBody } from "./connect-page.js";

export const logo = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" rx="56" fill="#14352b"/><rect x="48" y="72" width="160" height="112" rx="16" fill="#f4f1ea"/><path d="M72 112h112M72 140h80M72 168h96" stroke="#14352b" stroke-width="12" stroke-linecap="round"/></svg>`;

const page = (title: string, body: string) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · Desk</title><link rel="icon" href="/icon.svg"><style>body{margin:0;background:#f6f4ef;color:#1c1915;font:17px/1.65 system-ui}main{max-width:840px;margin:40px auto;padding:24px}a{color:#0c6b4d}h1{line-height:1.15;font-size:40px}h2{margin-top:32px}h3{margin:18px 0 6px}nav,footer{display:flex;flex-wrap:wrap;gap:18px}section{border:1px solid #ddd6c8;border-radius:16px;padding:22px;margin:22px 0;background:#fff}input,textarea,select,button{font:inherit;box-sizing:border-box;max-width:100%;padding:10px;border:1px solid #c9c0b2;border-radius:8px;background:#fff;color:inherit}input,textarea{width:100%}label{display:block;margin:12px 0}button{cursor:pointer;margin:12px 8px 12px 0}code,pre{overflow-wrap:anywhere}pre{overflow:auto;background:#fff;padding:12px;border-radius:8px}#message{white-space:pre-wrap}small{color:#5c564c}</style></head><body><main><nav><a href="/app">Desk workspace</a><a href="/connect">Connect an assistant</a><a href="/support">Support</a></nav><h1>${title}</h1>${body}<footer><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/data">Your data</a></footer></main></body></html>`;


function logoFile(): string {
  const candidates = [
    path.resolve(process.cwd(), "logo.jpg"),
    path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "logo.jpg"),
    path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "logo.jpg"),
    path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "logo.jpg")
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate;
  }
  return candidates[0];
}

export function installPublicPages(app: Express, baseUrl: string, supabaseUrl: string, anonKey: string) {
  app.get("/access", (_req, res) => res.type("html").send(page("Desk access", `<p>Support tools are available to Desk accounts with an active Pro subscription or a 14-day trial. This connection has no support-tool entitlement at present. It cannot change your plan or start a purchase. Desk does not print a price.</p><p>Verify that you connected the intended account. <a href="/connections">Manage the connection</a> or <a href="/support">contact support</a> if access looks incorrect.</p>`)));
  app.get("/icon.svg", (_req, res) => res.type("svg").send(logo));
  app.get(["/logo.jpg", "/favicon.ico"], (_req, res) => {
    res.type("image/jpeg");
    res.sendFile(logoFile());
  });
  app.get("/connect", (_req, res) => res.type("html").send(page("Connect an assistant", connectPageBody(baseUrl))));
  app.get("/privacy", (_req, res) => res.type("html").send(page("Privacy policy", `<p>Effective October 5, 2026. Desk is operated by Ouroboros Apps / Lawrence Hutchins. Contact the operator through the <a href="/support">private support form</a>.</p><h2>Information we process</h2><p>We process account identifiers and email provided at sign-in, subscription status and billing references, and support policy you intentionally save: approved answers, refund rules, escalation limits, and commitments (approved feature or timeline statements). Support requests contain the reply email and message you provide.</p><p>We do not receive every conversation automatically. Tools receive only their submitted arguments. Do not include passwords, payment card details, or unrelated personal information in policy text.</p><h2>Why and where</h2><p>We use this information to provide Desk, authenticate users, enforce subscriptions, respond to support, prevent abuse, and meet legal obligations. Supabase provides authentication and database hosting; Vercel hosts the service; Google provides optional sign-in; Stripe processes payments. We do not store complete card numbers. Connected MCP clients, including ChatGPT, Claude, Gemini, Grok, Cursor, and other hosts you authorize, receive the policy information their authorized tools request and apply their own privacy terms. Service providers may process information outside your country.</p><h2>Control and retention</h2><p>We do not sell policy content or use it to train our own models. Saved desks remain until you delete them or request account deletion. <a href="/data">Export or delete a desk</a>, including after a subscription expires. Desk deletion removes the live desk and its approved answers, refund rules, escalation limits, and commitments; provider backups may persist according to provider retention and are not an instant erasure guarantee. Billing records may be retained for required accounting or dispute handling.</p><p>Use support to request account deletion, correction, access, or questions about retention. Support records are kept while resolving the request and as needed for security or legal obligations. The service uses sign-in storage to maintain your session; unfinished workspace drafts are local to the current tab. No advertising trackers are included.</p><h2>Security and changes</h2><p>Account authentication and database ownership rules protect private desks. No service can promise absolute security. We publish policy changes here with an updated effective date. If local privacy law gives you additional rights, you may exercise them through support.</p>`)));
  app.get("/terms", (_req, res) => res.type("html").send(page("Terms of service", `<p>Effective October 4, 2026. These terms govern Desk, offered under the Hutchins App Studio brand. Questions and requests go through <a href="/support">support</a>.</p><h2>Your policy</h2><p>You retain your rights in content you submit. You grant the operator permission to host, process, retrieve, and transmit it only as needed to provide the service. Submit only content you have the right to use. Do not use the service unlawfully, attempt unauthorized access, or disrupt other users.</p><h2>Accounts and paid access</h2><p>Use your own account and protect your sign-in. Support tools require Desk Pro or an active 14-day trial. Plan terms, billing interval, trial end, and payment terms are shown by Stripe before purchase. This site does not print a price. Trials may convert to recurring paid subscriptions as disclosed at checkout. Manage cancellation through the billing portal in your account. Cancellation does not automatically delete your data. Contact support for billing mistakes or refund requests. Applicable consumer rights continue to apply.</p><h2>Desk has limits</h2><p>The assistant chooses when to invoke tools, subject to your permissions. Desk refuses a refund, feature, or timeline that is not in the approved set. It cannot promise that every host will call the tools, or that a model will follow a refusal. Review important replies before they are sent to a customer.</p><h2>Service operation</h2><p>We may change features or restrict access to address abuse, security issues, nonpayment, or legal obligations. We aim to provide reliable access but cannot guarantee uninterrupted operation or error-free assistant output. These terms do not remove rights or remedies that applicable law does not permit us to exclude.</p><h2>Leaving</h2><p>You can disconnect applications, export or delete desks, cancel billing, and request account deletion. These are separate controls, described on <a href="/data">Your data</a>.</p>`)));
  app.get("/support", (_req, res) => res.type("html").send(page("Contact Desk", `<section><h2>Use with Grok</h2><ol><li>Go to <a href="https://grok.com/connectors">grok.com/connectors</a>.</li><li>Choose New Connector → Custom.</li><li>Paste <code>https://desk-mcp-continuity2.vercel.app/mcp</code>.</li><li>Sign in.</li></ol><p>Full install steps for every assistant are on <a href="/connect">Connect an assistant</a>.</p></section><p>Send a private support, billing, privacy, or account-deletion request. Include a reply email. Do not send passwords, tokens, or payment card details.</p><form id="support"><label>Reply email<input name="email" type="email" required maxlength="254"></label><label>How can we help?<textarea name="message" required minlength="10" maxlength="4000" rows="7"></textarea></label><button>Send request</button></form><p id="message" role="status"></p><script>document.getElementById('support').onsubmit=async function(e){e.preventDefault();var b=this.querySelector('button');b.disabled=true;try{var r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:this.email.value,message:this.message.value})});var d=await r.json();if(!r.ok)throw Error(d.error||'Unable to send');document.getElementById('message').textContent='Request received. Reference: '+d.id;this.reset()}catch(e){document.getElementById('message').textContent=e.message}finally{b.disabled=false}};</script>`)));
  app.get("/data", (_req, res) => {
    const config = JSON.stringify({ url: supabaseUrl, key: anonKey }).replace(/</g, "\\u003c");
    res.type("html").send(page("Your data", `<p>Export a desk archive or permanently delete a desk and its approved answers, refund rules, escalation limits, and commitments. These controls remain available after Pro expires. <a href="/app">Sign in first</a>. <a href="/connections">Disconnect applications</a> separately. Manage cancellation in your account billing portal.</p><section><label>Desk id<input id="deskId" autocomplete="off"></label><button id="export" type="button">Download JSON archive</button><button id="remove" type="button">Permanently delete desk</button><p id="message" role="status"></p></section><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.115.0/dist/umd/supabase.js"></script><script>var cfg=${config};document.getElementById('export').onclick=function(){run(false)};document.getElementById('remove').onclick=function(){if(!confirm('Delete this desk and its approved policy?'))return;run(true)};async function run(remove){var status=document.getElementById('message');status.textContent='Working…';try{if(!cfg.url||!cfg.key||!window.supabase)throw Error('Sign-in is not configured yet.');var client=window.supabase.createClient(cfg.url,cfg.key);var session=await client.auth.getSession();if(!session.data.session)throw Error('Sign in to Desk first.');var desk=document.getElementById('deskId').value.trim();if(!desk)throw Error('Enter a desk id.');var path=remove?'/api/workspace/desks/'+encodeURIComponent(desk):'/api/workspace/export?deskId='+encodeURIComponent(desk);var r=await fetch(path,{method:remove?'DELETE':'GET',headers:{Authorization:'Bearer '+session.data.session.access_token}});var d=await r.json();if(!r.ok)throw Error(d.error||'Request could not complete.');if(remove){status.textContent='Desk deleted.';return}var url=URL.createObjectURL(new Blob([JSON.stringify(d.data,null,2)],{type:'application/json'}));var a=document.createElement('a');a.href=url;a.download='desk-export.json';a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000);status.textContent='Archive downloaded.'}catch(e){status.textContent=e.message}}</script>`));
  });
}

export { page };
